version: '3'
services:
  telegram-bot-manager:
    container_name: telegram-bot-manager
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    env_file:
      - .env
    restart: always
